name: Java CI-CD with Gradle and Azure

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-jars
        path: |
          build/libs
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/azure.key
        chmod 600 ~/.ssh/azure.key
        cat >>~/.ssh/config <<END
        Host azure
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/azure.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
    - name: Stop the bot
      run: ssh azure "sudo pkill -f 'java -jar'"
    - name: Upload jar on Azure VM
      run: |
        ssh azure 'echo "/usr/lib/jvm/java-16-openjdk-amd64/bin/java -jar /EdtBot/EdtBot-1.0-all.jar ${{ secrets.BOT_TOKEN }} >> /EdtBot/log.txt 2>> /EdtBot/log.txt" > /EdtBot/run.sh'
        ssh azure 'chmod 700 /EdtBot/run.sh'
        scp build/libs/EdtBot-1.0-all.jar azure:/EdtBot
    - name: Start the bot
      run: ssh azure 'cd /EdtBot ; sudo ./run.sh > /dev/null' &
